/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import java.awt.BorderLayout;
import java.awt.event.*;
import java.io.File;
import javax.media.opengl.awt.GLCanvas;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JFileChooser;
import javax.swing.LayoutStyle;
import javax.swing.filechooser.FileFilter;
import volume.Volume;
import volvis.RaycastRenderer;
import volvis.Visualization;

/**
 *
 * @author michel
 */
public class VolVisApplication extends javax.swing.JFrame {

    Visualization visualization;
    Volume volume;
    RaycastRenderer raycastRenderer;
    
    /**
     * Creates new form VolVisApplication
     */
    public VolVisApplication() {
        initComponents();
        this.setTitle("Volume visualization");
        
        // Create a new visualization for the OpenGL panel
        GLCanvas glCanvas = new GLCanvas();
        renderPanel.setLayout(new BorderLayout());
        renderPanel.add(glCanvas, BorderLayout.CENTER);
        visualization = new Visualization(glCanvas);
        glCanvas.addGLEventListener(visualization);

        raycastRenderer = new RaycastRenderer();
        visualization.addRenderer(raycastRenderer);
        raycastRenderer.addTFChangeListener(visualization);
        tabbedPanel.addTab("Raycaster", raycastRenderer.getPanel());
        tabbedPanel.addTab("Transfer Function Editor", raycastRenderer.getOwPanel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        splitPane = new JSplitPane();
        tabbedPanel = new JTabbedPane();
        loadVolume = new JPanel();
        loadButton = new JButton();
        jScrollPane1 = new JScrollPane();
        infoTextPane = new JTextPane();
        renderPanel = new JPanel();

        //======== this ========
        setDefaultCloseOperation(3);
        Container contentPane = getContentPane();

        //======== splitPane ========
        {
            splitPane.setDividerLocation(600);

            //======== tabbedPanel ========
            {

                //======== loadVolume ========
                {


                    //---- loadButton ----
                    loadButton.setText("Load volume");
                    loadButton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            loadButtonActionPerformed(e);
                        }
                    });

                    //======== jScrollPane1 ========
                    {

                        //---- infoTextPane ----
                        infoTextPane.setEditable(false);
                        jScrollPane1.setViewportView(infoTextPane);
                    }

                    GroupLayout loadVolumeLayout = new GroupLayout(loadVolume);
                    loadVolume.setLayout(loadVolumeLayout);
                    loadVolumeLayout.setHorizontalGroup(
                        loadVolumeLayout.createParallelGroup()
                            .addGroup(loadVolumeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(loadVolumeLayout.createParallelGroup()
                                    .addComponent(jScrollPane1)
                                    .addGroup(loadVolumeLayout.createSequentialGroup()
                                        .addComponent(loadButton)
                                        .addGap(0, 265, Short.MAX_VALUE)))
                                .addContainerGap())
                    );
                    loadVolumeLayout.setVerticalGroup(
                        loadVolumeLayout.createParallelGroup()
                            .addGroup(loadVolumeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loadButton)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                .addContainerGap())
                    );
                }
                tabbedPanel.addTab("Load", loadVolume);
            }
            splitPane.setRightComponent(tabbedPanel);

            //======== renderPanel ========
            {

                GroupLayout renderPanelLayout = new GroupLayout(renderPanel);
                renderPanel.setLayout(renderPanelLayout);
                renderPanelLayout.setHorizontalGroup(
                    renderPanelLayout.createParallelGroup()
                        .addGap(0, 750, Short.MAX_VALUE)
                );
                renderPanelLayout.setVerticalGroup(
                    renderPanelLayout.createParallelGroup()
                        .addGap(0, 750, Short.MAX_VALUE)
                );
            }
            splitPane.setLeftComponent(renderPanel);
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addComponent(splitPane)
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("E:\\Visualization (2IV35)\\Assignments\\Assignment 2\\set2\\set2_data");
        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isFile()) {
                    if (f.getName().toLowerCase().endsWith(".fld")) {
                        return true;
                    }
                }
                if (f.isDirectory()) {
                    return true;
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "AVS files";
            }
        });
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                volume = new Volume(file);
                
                String infoText = new String("Volume data info:\n");
                infoText = infoText.concat(file.getName() + "\n");
                infoText = infoText.concat("dimensions:\t\t" + volume.getDimX() + " x " + volume.getDimY() + " x " + volume.getDimZ() + "\n");
                infoText = infoText.concat("voxel value range:\t" + volume.getMinimum() + " - " + volume.getMaximum());
                infoTextPane.setText(infoText);
                raycastRenderer.setVolume(volume);
                visualization.update();

        }
    }//GEN-LAST:event_loadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolVisApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolVisApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolVisApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolVisApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolVisApplication().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSplitPane splitPane;
    private JTabbedPane tabbedPanel;
    private JPanel loadVolume;
    private JButton loadButton;
    private JScrollPane jScrollPane1;
    private JTextPane infoTextPane;
    private JPanel renderPanel;
    // End of variables declaration//GEN-END:variables
}
